name: Release

on:
  push:
    # Release from tags (which are created from GitHub releases too)
    tags:
      - '/v[0-9]+(\.[0-9]+)*(-alpha\.[0-9]+)?/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then make install; fi
    - name: Lint with flake8
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Release package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: {{ secrets.TWINE_API_TOKEN }}
      run: |
        make release
